apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - aws-load-balancer-controller.yaml
  - cert-manager.yaml
  - monitoring.yaml

commonLabels:
  environment: production
  managed-by: flux